### ISSUE TITLE
中文输入法下，预期之外的语言切换提示

### ISSUE THREAD

**Issue by Gilgamesh-lzq** [JiagengDing/hammerspoon-config#1]
‍你好，我注意到你的演示视频中切换输入法的提示会连续出现很多，影响观感。我对你的代码进行了一点点改良，解决了这个问题https://github.com/Gilgamesh-lzq/my_hammer_spoon_script 。但这个过程中我观察到了另一个问题，在英文输入法下，如果我点击“系统偏好设置”或者任务栏上其他任何东西，不会有问题；但是在中文输入法下，进行同样的操作时，每一次鼠点击都会提示切换为中文输入法，非常的烦人。但我没给任何系统软件设置默认语言，而且我代码中对中英文输入法的处理是一样的，我不理解为什么会有这样不一致的现象。或许您曾经遇到过这个问题或者也试图解过这个问题？我们可以讨论一下吗

**Comment by JiagengDing** [comment]
你好，我目前更新了Moterey之后，使用karabiner将fn键映射到了右command键后切换输入法的提示变为了系统默认提示，并且没有出现点击任务栏错误切换的问题，可能是你的系统版本问题？

**Comment by Quincy-Leo** [comment]
是的，是我的问题，我弄错了。我在我的代码里添加了「手动切换输入法时给出弹窗提示」的功能但是没有处理好运行逻辑。在您的代码中没有「全局的任何输入法切换都会提示」的功能，所以完全不会有那个问题。我也已经在我最新版的代码中修复了BUG。谢谢您。
